### PR TITLE
Detour LUA traces

### PR DESCRIPTION
**Pull request by WasabiThumb**
Does what it says. It targets util.TraceLine, I may add overrides for TraceHull or TraceEntity in the future but that would be significantly more difficult. The main benefit of this is that many addons or even internal modules use util.TraceLine, chiefly, for a LOT of logic. You can now, for instance, look at yourself through a portal and see your name and health show up on your crosshair as if you were another player. This is because the module that controls that behavior uses util.TraceLine.

Another fun application of this would be allowing you to shoot portals through other portals with the portal gun. All that would need to be done is to remove the filter for seamless portals (well, it's 3 lines more complicated than that). I've tried it myself and it was really cool, however that is the kind of design decision that the creator should have discretion over.

I've added a 4-layer recursion limit, there's no real reason for this other than that 4 is the default portal depth in Portal.

### CODE REVIEW

**Comment by WasabiThumb** [comment]
[Watch a demo here](https://streamable.com/sdxb6a)

**Comment by shadow7483147** [comment]
I dropped this file in my autorun folder but it breaks being able to walk through to the other side of the portal.

**Comment by WasabiThumb** [comment]
> I dropped this file in my autorun folder but it breaks being able to walk through to the other side of the portal.

I'm not one to be presumptuous but I think you've probably done something wrong. It works fine for me, I suggest re-downloading [the whole thing from my fork](https://github.com/WasabiThumb/GMod-Seamless-Portals/archive/refs/heads/main.zip) and replacing the plugin, in your plugins folder.

In general you don't want to be putting plugin files in the garrysmod directory. If you meant the autorun folder inside of the addon directory, then that's fine I suppose and I'm not sure what went wrong. Any errors in console?

**Comment by WasabiThumb** [comment]
If none of that works, then give steps to reproduce/any console errors and I'll get to work on fixing it. I'm not sure how this would affect the portal functionality, as it is a completely new, isolated file I've added in this PR. Maybe you replaced an existing one?

**Comment by shadow7483147** [comment]
https://user-images.githubusercontent.com/3190007/156670945-41a3411a-fe4c-4b97-8558-58b4a8036f3b.mp4

No errors in the console.

**Comment by WasabiThumb** [comment]
Okay, working on fixing it now

**Comment by WasabiThumb** [comment]
It's "fixed". If this PR is merged, it will be necessary to either set noDetour to true in the Trace arguments or to add relevant portals to the filter in order to bypass the detour code in the future.

**Comment by Mee12345** [comment]
probably will accept this pr, but will do heavy modifications if thats fine with you

**Comment by WasabiThumb** [comment]
No, I don't mind modifications at all. This will for sure cause some visual strangeness, like for "line from start pos to trace hit pos" operations (going to go in some strange direction) but I think it's an overall improvement. It plays well with my mountain of addons which is the best stress test that I can personally devise

**Pull request merged**
