### PR TITLE
hacky fix for black artifacts

### PR DESCRIPTION
**Pull request by homonovus**
fixes the black artifacts when looking through portals while grabbing an entity with the physgun

### CODE REVIEW

**Comment by Mee12345** [comment]
this looks like a better implementation, will probably pr

**Comment by Mee12345** [comment]
can you fix effects_freeze and effects_unfreeze too? I cant seem to get it working for some reason

**Review by Enderman1444 — APPROVED** [review]

**Comment by WasabiThumb** [comment]
You can turn off freeze/unfreeze effects entirely like so:
```
local oldUtilEffect = util.Effect
local function effect(name, b, c, d)
     if (name == "phys_freeze" or name == "phys_unfreeze") then return end
     oldUtilEffect(name, b, c, d)
end
util.Effect = effect
```
That is both _very_ hacky and not ideal

**Comment by WasabiThumb** [comment]
If you have an adversion to manipulating convars, then maybe PreDrawHalos is what you want? Especially since I think I've had issues with non-physgun halos

**Comment by Mee12345** [comment]
combined both of ur ideas into 1 thing, the issue is completely fixed :)
(both of u guys are credited ofc)

**Pull request closed without merging**
