### PR TITLE
Add more spawnmenu options

### PR DESCRIPTION
**Pull request by WasabiThumb**
Uses a somewhat overengineered system to add more spawnmenu options while also not creating tons of dummy entities. Has an easily expandable API if you wish to add more. Here's what it has currently.

image
image

### CODE REVIEW

**Comment by Mee12345** [comment]
I like this

**Comment by Mee12345** [comment]
ive decided since we have the portal creator & resizer that this isnt necessary

**Comment by Mee12345** [comment]
Thanks anyway for taking the time to make this system

**Comment by WasabiThumb** [comment]
Yep felt the same way

**Pull request closed without merging**
