### PR TITLE
Portal creator tool

### PR DESCRIPTION
**Pull request by WasabiThumb**
My voice came out very quiet on the video not sure why
[Demo and some comments](https://streamable.com/y5rtth)

### CODE REVIEW

**Comment by Mee12345** [comment]
ok this is actually cool I will def pr this

**Comment by Mee12345** [comment]
can you add CPPI checks aswell? Or I can do it

**Comment by WasabiThumb** [comment]
Gotta be honest, I haven't the slightest clue what CPPI is. If I'm referencing code that uses CPPI calls, I typically try to carry them over. But I have no idea what they do. Where do you want the checks?

**Comment by Mee12345** [comment]
its basically prop protection, all you need to know is to check for CPPI, if valid set the owner to that prop using SetCPPIOwner (or whatever its called) and make sure that you cant toolgun props that arent yours

**Comment by WasabiThumb** [comment]
Okay, I added them based on this [strange spec](https://ulyssesmod.net/archive/CPPI_v1-1.pdf) I eventually found. Still not sure what mods have the CPPI spec in them in order to test it out (I guess they don't advertise it). Probably ULX?

**Comment by WasabiThumb** [comment]
Still need to test after making those changes will update later today

**Comment by Mee12345** [comment]
successfully added into the mod with some minor changes, you are also credited in the desc

**Pull request merged**
