### PR TITLE
Added: Optimization for some of the files

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Hey there, @Mee12345 

Added more optimizations

**Comment by dvdvideo1234** [comment]
Hey, @Mee12345 Will test this today in the evening and share results here

**Comment by dvdvideo1234** [comment]
Works. Gained a bit of frames too ;)

**Comment by dvdvideo1234** [comment]
The NPC is at the other side. The laser goes to the other portal comes here and reflects from gm_construct's mirror material

**Comment by Mee12345** [comment]
what're the results of this? any data?

**Comment by dvdvideo1234** [comment]
Only for the `ShouldRender` function. The rest just avoid creating objects every frame, and code repetition. Function `sin` and `cos` are calculated using infinite series, so calculate once and use multiple times. I can so an FPS test. What test do you have in mind ?

It should be generally better though.

**Comment by dvdvideo1234** [comment]
Testing methodology: Continue spawning portals with the toolgun until get single-digit frame rate.
Count down the amount of entities spawned:

Running `gm_construct` with no portal spawned: 472

**Comment by dvdvideo1234** [comment]
Hey, @Mee12345 It is about 12% faster now. Again it depends what is called and when ;)

**Comment by dvdvideo1234** [comment]
```
Test finished all 3 cases successfully!
Overall testing rank list summary:
[         21.987]: original > return not (e:GetClass() == "seamless_portal" or e:GetClass() == "player")
[          3.122]: modified > return not (seamless_table[e:GetClass()] or false)
[          3.249]: modif-IF > if(seamless_table[e:GetClass()]) then return false end; return true
```

**Comment by Mee12345** [comment]
looks good, ill accept & push when I get time to test myself

**Comment by dvdvideo1234** [comment]
Do you prefer tabs or spaces.. Most of the files have utilized both indentations. Still will be good to equalize to eather one, but it is better in the next PR.

**Pull request merged**
