### PR TITLE
Apply: Comments beautifier and library consolidation

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Added: Convar flags for separate and server controlled convars to library
Optimized: Add material to library so it can be used in other sources
Rearange: `TransformPortal` Shorten variable names and return created zero vectors. Use angle copy instead of assign

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
It has to use a `SOLID` enum for not to break physics when the value of the solid is changed.

**Comment by dvdvideo1234** [comment]
This consolidates the library and ditches the dedicated local function inside every sent making it a lot nicer. Remove the functions and send them to the dedicated library.

**Comment by dvdvideo1234** [comment]
https://user-images.githubusercontent.com/9112662/159005867-3cc760e8-f822-4baf-8017-7dbde782dac8.mp4

**Comment by dvdvideo1234** [comment]
Hello @Mee12345 

What changes do you require to merge this. As I see you are worried about calling a global table is a tiny bit slower. I can:
1. Localize the `SeamlessPortals` library reference
 * Anyone will be able to add custom methods to it
 * If they replace a method and crash the addon it is their fault ;)
2. Localize the the library functions themselves by doing `local setPlacement = SeamlessPortals.SetPortalPlacement`:
 * This will reduce the extra method hash lookup and improve performance
 * You have to reload the other files that depend on the library when you develop them
 3. Use the old style of making modules:
  * This thing is [less secure](https://www.tutorialspoint.com/lua/lua_modules.htm)
  * Some systems have [deprecated](https://www.techopedia.com/definition/24828/deprecated) this to some extend.
4. Use the new style of making the module ( [First example](https://www.tutorialspoint.com/lua/lua_modules.htm) ) 
  * It is more secure
  * It is not deprecated
  * Files will use their own reference to the library

**Comment by Mee12345** [comment]
hm, ok
personally I like option 1, but id have to playtest your fork to make sure it works exactly the same, (or hopefully smoother) since any small imperfect detail (mostly when teleporting) ruins the immersion of the portals

**Pull request closed without merging**
